version = 0.1
[default.pipeline_bootstrap.parameters]
oidc_provider_url = "https://token.actions.githubusercontent.com"
oidc_client_id = "sts.amazonaws.com"
github_org = "albertsuwandhi"
github_repo = "sam-hello-world"
deployment_branch = "main"
oidc_provider = "github-actions"
permissions_provider = "OpenID Connect (OIDC)"

[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::004722542845:role/aws-sam-cli-managed-dev-pipel-PipelineExecutionRole-7ZX00IRWUmyy"
cloudformation_execution_role = "arn:aws:iam::004722542845:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionRo-NddYtErFRpXk"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-r-artifactsbucket-dmudntnearb9"
image_repository = ""
region = "ap-southeast-1"
